export {default as Onboarding} from "./Onboarding"
export {default as PhoneRegister} from "./auth/PhoneRegister"
export {default as OTP} from "./auth/OTP"
export {default as ProfileCreate} from "./auth/ProfileCreate"
export {default as UserToFollow} from "./main/UserToFollow"
export {default as ChatHome} from "./main/ChatHome"
export {default as Profile} from "./main/Profile"